name: mercadopago_sdk
description: >-
  Mercadopago SDK module for Payments integration
  for use in applications web, server, flutter
homepage: https://github.com/QasimWaheed/mercadopago_sdk2
version: 1.3.0
publish_to: none

dependencies:
  http: ^1.2.1
  test: ^1.25.5

environment:
  sdk: ">=2.12.0 <3.0.0"
